name: Build

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Install deps
      run: sudo apt-get install -y libbz2-dev

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.22.0
      # env:
      #   CIBW_SOME_OPTION: value
      #    ...
      # with:
      #   package-dir: .
      #   output-dir: wheelhouse
      #   config-file: "{package}/pyproject.toml"

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
    #     path: ./wheelhouse/*.whl
