name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: >
            ${{ format('pre-commit-{0}-{1}',
            steps.setup-python.outputs.python-version,
            hashFiles('.pre-commit-config.yaml')
            ) }}

      - name: Install pre-commit
        run: |
          pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit hooks
        working-directory: ${{ inputs.working-directory }}
        run: |
          git ls-files | xargs pre-commit run \
                          --show-diff-on-failure \
                          --color=always \
                          --files
